server:
  port: 7002

spring:
  application:
    name: insist-gateway

  cloud:

    loadbalancer:
      ribbon:
        enabled: true

    #nacos
    nacos:
      discovery:
        server-addr: http://localhost:8848/

    #consul注册
    consul:
      host: www.insist-cloud.com
      port: 8500
      discovery:
        service-name: ${spring.application.name}

    #zookeeper注册
    zookeeper:
      connect-string: 39.108.172.78:2181,39.108.172.78:2182,39.108.172.78:2183
      discovery:
        enabled: true
        register: true

    #gateway
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://insist-service-daily6003
          predicates:
            - Path=/v1/daily/** # 断言，路径相匹配的进行路由

        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://insist-service-emp6001
          predicates:
            - Path=/vi/** #断言,路径相匹配的进行路由
            - After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
          #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
          #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://www.insist-cloud.com:9000/eureka/
      #集群
  #      defaultZone: http://www.insist-eureka01.com:9001/eureka/,http://www.insist-eureka02.com:9002/eureka/,http://www.insist-eureka03.com:9003/eureka/
  instance:
    instance-id: insist-service-finance6002
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2