server:
  port: 6001


spring:
  application:
    name: insist-service-emp6001

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://www.insist-cloud.com:9000/eureka/
#      集群
#      defaultZone: http://www.insist-eureka01.com:9001/eureka/,http://www.insist-eureka02.com:9002/eureka/,http://www.insist-eureka03.com:9003/eureka/
  instance:
    instance-id: insist-service-emp6001
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2