server:
  port: 3001

spring:
  application:
    name: insist-config
  #rabbit相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: bitnami
  cloud:
    #config
    config:
      server:
        git:
          #uri: git@github.com:EiletXie/config-repo.git #Github上的git仓库名字
          uri: https://github.com/EiletXie/config-repo.git
          ##搜索目录.这个目录指的是github上的目录
          search-paths:
            - config-repo
      ##读取分支
      label: master

    #consul注册
    consul:
      host: www.insist-cloud.com
      port: 8500
      discovery:
        service-name: ${spring.application.name}

    #zookeeper注册
    zookeeper:
      connect-string: 39.108.172.78:2181,39.108.172.78:2182,39.108.172.78:2183
      discovery:
        enabled: true
        register: true


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机
      defaultZone: http://www.insist-cloud.com:9000/eureka/
      #集群
  #      defaultZone: http://www.insist-eureka01.com:9001/eureka/,http://www.insist-eureka02.com:9002/eureka/,http://www.insist-eureka03.com:9003/eureka/
  instance:
    instance-id: insist-service-finance6002
    prefer-ip-address: true #访问路径可以显示ip
    #Eureka客户端向服务端发送心跳的实际间隔，单位为秒（默认为30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上线，单位为秒（默认为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2



#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
